name: Rust

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install scoop
        run: iwr -useb get.scoop.sh | iex
        
      - name: Test
        run: scoop
