name: Rust

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install stuff
        run: |
          choco install llvm
          echo "##[add-path]C:\Program Files\LLVM\bin"

      - name: Test
        run: clang
      
