name: Rust

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install stuff
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install aria2
          scoop install llvm
          
      - name: RefreshEnv
        run: RefreshEnv
      
      - name: Test
        run: scoop
